### ISSUE TITLE
Investigate Flutter UI

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#11]
It would be awesome to boot up the beaglebone and be able to connect to it wirelessly and have a custom UI pop up when we connect. But how would we accomplish this?

Goals:
- investigate the available approaches to connect and have a custom UI for the beaglebone
- create subtasks either for further investigation and/or development tasks

Basically I'm looking for someone to take the lead on interfacing between the hardware and UI.

**Comment by DeclanBruce** [comment]
I found a "home control center" project that appears to use Python and Flask in order to set up a web server on the BeagleBone Green Wireless so that users can view sensor data from a web browser. Figured I would leave this here for reference in case others found it useful. It is notably not that new. It looks like he made this project right after the BBGW was released back in May 2016:
[BBGW - Home Control Center](https://github.com/Lee-Kevin/19.HomeControlCenterBBGW)
