### ISSUE TITLE
Webserver & Database investigation

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#13]
find out how we can use C++ to interface with a webserver/database. results must have a test program working.

#TODO

**Comment by anthony-bartman** [comment]
**Installing Flask:**
Login as root with ```sudo -s```
1. We will not need cloud9 as our web thing.  To uninstall it use ```apt-get remove c9-core-installer``` and type in yes
2. Then uninstall nodeJS with ```apt-get remove nodejs``` and type in yes
3. Remove X Server with ```apt-get remove --purge libx11-6```
4. This apt-get autoremove --purge
5. Remove Node-Red   apt-get remove --purge bb-node-red-installer
6. apt-get remove --purge c9-core-installer
7. cd /var/lib  -> rm -r node-red   -> rm -r cloud9

**Comment by DeclanBruce** [comment]
I found a "home control center" project that appears to use Python and Flask in order to set up a web server on the BeagleBone Green Wireless so that users can view sensor data from a web browser. Figured I would leave this here for reference in case others found it useful. It is notably not that new. It looks like he made this project right after the BBGW was released back in May 2016:
[BBGW - Home Control Center](https://github.com/Lee-Kevin/19.HomeControlCenterBBGW)
